/**
 * MChip Advance CVN 18 mapper.
 *
 * Takes the existing `IssuerProfileForSad` + `CardData` shapes (which
 * the legacy SADBuilder consumes) and produces a `ParamBundleInput`
 * that the ParamBundle builder can serialise.  This is the bridge
 * between "what data-prep has today" and "what PA v3 expects".
 *
 * Scope: MChip Advance CVN 18 only.  Other CVNs / schemes throw.  When
 * the prototype extends to Visa VSDC, add `scheme-vsdc.ts` alongside
 * this with the same interface; data-prep picks the mapper based on
 * IssuerProfile.scheme.
 */

import type { IssuerProfileForSad, CardData } from './sad-builder.js';
import {
  buildParamBundle,
  parseParamBundle,
  type ParamBundleInput,
} from './param-bundle-builder.js';

// ---------------------------------------------------------------------------
// MChip CVN 18 constants
// ---------------------------------------------------------------------------

/** CVN byte as it appears inside IAD and as a standalone ParamBundle tag. */
export const MCHIP_CVN_18 = 0x12;

/** Accepted CVN variants for MChip Advance. */
const MCHIP_SUPPORTED_CVNS = new Set([10, 17, 18]);

/**
 * Map an `IssuerProfileForSad` + `CardData` + chip-keys + chip-certs
 * bundle into a `ParamBundleInput` suitable for MChip CVN 18.
 *
 * This is a pure transform — no I/O, no crypto side-effects.  Anything
 * that requires HSM / KMS / APC (key derivation, cert signing) happens
 * upstream in data-prep; the result is passed in here as bytes.
 */
export interface McipMapperInput {
  /** Per-profile EMV constants (from IssuerProfile row). */
  profile: IssuerProfileForSad;
  /** Per-card data (PAN, expiry, etc.). */
  card: CardData;

  /** 16-byte MK-AC derived by APC from issuer master + PAN/PSN. */
  mkAc: Buffer;
  /** 16-byte MK-SMI. */
  mkSmi: Buffer;
  /** 16-byte MK-SMC. */
  mkSmc: Buffer;

  /** PKCS#1 DER ICC RSA private key generated by APC. */
  iccRsaPriv: Buffer;
  /** Server-signed ICC PK Certificate (Tag 9F46). */
  iccPkCert: Buffer;

  /** 4-byte bank ID (big-endian). */
  bankId: number;
  /** 4-byte program ID. */
  progId: number;
  /** Hostname the PA applet bakes into post-activation NDEF URLs. */
  postProvisionUrl: string;
}

/**
 * Validate + transform a McipMapperInput into a ParamBundleInput.
 *
 * Validation:
 *   - Scheme must be 'mchip_advance'
 *   - CVN must be in MCHIP_SUPPORTED_CVNS
 *   - All required hex-encoded issuer-profile constants must be
 *     present and non-empty (AIP, AFL, CVM list, IACs, AUC, currency
 *     code/exponent, country code, app version, AID, CA PK index)
 *   - MK lengths must be 16 bytes each
 */
export function mapMChipToParamBundle(input: McipMapperInput): ParamBundleInput {
  const { profile, card } = input;

  if (profile.scheme !== 'mchip_advance') {
    throw new Error(
      `scheme-mchip: expected scheme 'mchip_advance', got '${profile.scheme}'`,
    );
  }
  if (!MCHIP_SUPPORTED_CVNS.has(profile.cvn)) {
    throw new Error(
      `scheme-mchip: CVN ${profile.cvn} not supported in prototype ` +
        `(supported: ${[...MCHIP_SUPPORTED_CVNS].join(', ')})`,
    );
  }
  // Prototype is locked to CVN 18 — warn (but don't hard-fail) if
  // anything else comes through so the applet side has a single
  // variant to validate against.
  if (profile.cvn !== 18) {
    // eslint-disable-next-line no-console
    console.warn(
      `[scheme-mchip] CVN ${profile.cvn} accepted but prototype is ` +
        `optimised for CVN 18 — applet may reject.`,
    );
  }

  const required: Array<[string, string | undefined]> = [
    ['aip', profile.aip],
    ['afl', profile.afl],
    ['cvmList', profile.cvmList],
    ['iacDefault', profile.iacDefault],
    ['iacDenial', profile.iacDenial],
    ['iacOnline', profile.iacOnline],
    ['appUsageControl', profile.appUsageControl],
    ['currencyCode', profile.currencyCode],
    ['currencyExponent', profile.currencyExponent],
    ['countryCode', profile.countryCode],
    ['appVersionNumber', profile.appVersionNumber],
    ['aid', profile.aid],
    ['caPkIndex', profile.caPkIndex],
    ['issuerPkCertificate', profile.issuerPkCertificate],
    ['issuerPkExponent', profile.issuerPkExponent],
  ];
  for (const [name, val] of required) {
    if (!val || val.length === 0) {
      throw new Error(`scheme-mchip: missing required IssuerProfile field '${name}'`);
    }
  }

  return {
    // Per-card
    pan: card.pan,
    psn: card.cardSequenceNumber,
    expiryYymm: card.expiryDate,
    effectiveYymm: card.effectiveDate,
    serviceCode: card.serviceCode,
    icvv: Buffer.from(card.icvv, 'hex'),

    // Scheme / CVN / AID
    scheme: 'mchip',
    cvn: MCHIP_CVN_18,
    aid: Buffer.from(profile.aid!, 'hex'),

    // Per-card HSM-derived keys
    mkAc: input.mkAc,
    mkSmi: input.mkSmi,
    mkSmc: input.mkSmc,

    // EMV constants from the profile
    aip: Buffer.from(profile.aip!, 'hex'),
    afl: Buffer.from(profile.afl!, 'hex'),
    auc: Buffer.from(profile.appUsageControl!, 'hex'),
    iacDefault: Buffer.from(profile.iacDefault!, 'hex'),
    iacDenial: Buffer.from(profile.iacDenial!, 'hex'),
    iacOnline: Buffer.from(profile.iacOnline!, 'hex'),
    cvmList: Buffer.from(profile.cvmList!, 'hex'),

    // Bank / program identity
    bankId: input.bankId,
    progId: input.progId,
    postProvisionUrl: input.postProvisionUrl,

    // ICC-side crypto (server-generated + server-signed for prototype)
    iccRsaPriv: input.iccRsaPriv,
    iccPkCert: input.iccPkCert,

    // Issuer-side PKI (public info the chip serves at POS time)
    issuerPkExp: Buffer.from(profile.issuerPkExponent!, 'hex'),
    issuerPkCert: Buffer.from(profile.issuerPkCertificate!, 'hex'),
    issuerPkRemainder: profile.issuerPkRemainder
      ? Buffer.from(profile.issuerPkRemainder, 'hex')
      : undefined,
    caPkIndex: Buffer.from(profile.caPkIndex!, 'hex'),

    // Optional display bits
    appLabel: profile.appLabel,
    appPreferredName: profile.appPreferredName,
    appVersion: Buffer.from(profile.appVersionNumber!, 'hex'),
    currencyCode: Buffer.from(profile.currencyCode!, 'hex'),
    currencyExponent: Buffer.from(profile.currencyExponent!, 'hex'),
    countryCode: Buffer.from(profile.countryCode!, 'hex'),
  };
}

/**
 * One-shot convenience: build the wire-ready ParamBundle bytes from a
 * mapper input, skipping the intermediate ParamBundleInput.
 */
export function buildMChipParamBundle(input: McipMapperInput): Buffer {
  return buildParamBundle(mapMChipToParamBundle(input));
}

// ---------------------------------------------------------------------------
// DGI simulator — "what the chip will commit to NVM"
// ---------------------------------------------------------------------------
//
// This is the TypeScript mirror of what PA v3's on-chip DGI builders
// produce.  It lets us:
//   1. Run byte-parity tests: the mirror output should match the legacy
//      SADBuilder's output for the same input.
//   2. Give the JavaCard dev a reference impl to port byte-for-byte.
//   3. Smoke-test mapper output without actual silicon.
//
// DGI layout for MChip CVN 18:
//   DGI 0101  App Data         AIP, AFL, AUC, PAN, Expiry, ...
//   DGI 0102  AFL (duplicate)  some MChip perso tooling expects it here
//   DGI 8201  Key slots        MK-AC, MK-SMI, MK-SMC, ICC PK cert, ICC RSA
//   DGI 9201  MChip scheme     CVR defaults, IACs, CVM list
//
// The legacy SADBuilder groups tags into whatever DGIs the ChipProfile
// specifies.  For byte parity, the ChipProfile used in production for
// MChip CVN 18 must match the layout above.

import { TLV } from './tlv.js';
import { Track2 } from './track2.js';

export interface SimulatedChipDgis {
  /** DGI 0x0101 — Application Data. */
  dgi0101: Buffer;
  /** DGI 0x0102 — AFL (duplicate). */
  dgi0102: Buffer;
  /** DGI 0x8201 — Key slots + ICC PK cert + ICC RSA priv. */
  dgi8201: Buffer;
  /** DGI 0x9201 — MChip scheme data. */
  dgi9201: Buffer;
}

/**
 * Simulate what the PA v3 applet produces on-chip when it parses the
 * bundle and builds DGIs.
 *
 * Invariant: for the same ParamBundle input, this function's output
 * bytes must match what the applet writes to NVM.  The applet spec
 * (applets/pa/.../DgiBuilderMchip.java) implements the same logic in
 * Java.  Any divergence = failed byte parity = chip won't transact
 * correctly at POS.
 */
export function simulateMChipChipBuild(bundle: Buffer): SimulatedChipDgis {
  const params = parseParamBundle(bundle);

  const must = (tag: number, name: string): Buffer => {
    const v = params.get(tag);
    if (!v) throw new Error(`simulate-mchip: missing required tag 0x${tag.toString(16)} (${name})`);
    return v;
  };

  // Pull the params we need.
  const pan = must(0x01, 'PAN');
  const psn = must(0x02, 'PSN');
  const expiry = must(0x03, 'EXPIRY');
  const effective = must(0x04, 'EFFECTIVE');
  const serviceCode = must(0x05, 'SERVICE_CODE');
  const aid = must(0x08, 'AID');
  const mkAc = must(0x09, 'MK_AC');
  const mkSmi = must(0x0a, 'MK_SMI');
  const mkSmc = must(0x0b, 'MK_SMC');
  const aip = must(0x0c, 'AIP');
  const afl = must(0x0d, 'AFL');
  const auc = must(0x0e, 'AUC');
  const iacDefault = must(0x0f, 'IAC_DEFAULT');
  const iacDenial = must(0x10, 'IAC_DENIAL');
  const iacOnline = must(0x11, 'IAC_ONLINE');
  const cvmList = must(0x12, 'CVM_LIST');
  const iccRsaPriv = must(0x16, 'ICC_RSA_PRIV');
  const iccPkCert = must(0x17, 'ICC_PK_CERT');
  const appVersion = must(0x1a, 'APP_VERSION');
  const currencyCode = must(0x1b, 'CURRENCY_CODE');
  const currencyExponent = must(0x1c, 'CURRENCY_EXPONENT');
  const countryCode = must(0x1d, 'COUNTRY_CODE');
  const icvv = must(0x1e, 'ICVV');

  // Optional params.
  const appLabel = params.get(0x18);

  // --- Recompute Track 2 equivalent data (Tag 57) ---
  // Track2.build takes (pan, expiryYymm, serviceCode) as digit strings.
  const panDigits = bcdToDigits(pan);
  const expiryYymm = bcdToDigits(expiry);
  // ServiceCode is stored as 4-nibble BCD (leading zero padded) so we
  // have even nibbles for byte alignment.  Decode all 4 nibbles then
  // take the last 3 digits (e.g. '0201' → '201').
  const serviceCodeAll = bcdToDigitsNoFPad(serviceCode);
  const serviceCodeDigits = serviceCodeAll.slice(-3);
  const track2 = Track2.build(panDigits, expiryYymm, serviceCodeDigits);

  // --- DGI 0101 — Application Data ---
  // Contains the standard EMV tags in TLV form.
  const dgi0101 = Buffer.concat([
    TLV.build(0x82, aip),
    TLV.build(0x94, afl),
    TLV.build(0x9f07, auc),
    TLV.build(0x5a, pan),
    TLV.build(0x5f24, Buffer.concat([expiry, Buffer.from([0x31])])), // YYMMDD (31 convention)
    TLV.build(0x5f25, Buffer.concat([effective, Buffer.from([0x01])])),
    TLV.build(0x57, track2),
    TLV.build(0x5f34, psn),
    TLV.build(0x84, aid),
    TLV.build(0x9f08, appVersion),
    TLV.build(0x9f42, currencyCode),
    TLV.build(0x9f44, currencyExponent),
    TLV.build(0x5f28, countryCode),
    ...(appLabel ? [TLV.build(0x50, appLabel)] : []),
  ]);

  // --- DGI 0102 — AFL duplicate ---
  const dgi0102 = TLV.build(0x94, afl);

  // --- DGI 8201 — Key slots ---
  // Proprietary tag numbers used by MChip:
  //   9F52 → MK-AC        (M/Chip uses this; older spec used 8E/DF01)
  //   9F53 → MK-SMI
  //   9F54 → MK-SMC
  //   9F46 → ICC PK Certificate
  //   DF73 → ICC RSA priv  (proprietary, unused by POS — for on-chip
  //                          signing only)
  const dgi8201 = Buffer.concat([
    TLV.build(0x9f52, mkAc),
    TLV.build(0x9f53, mkSmi),
    TLV.build(0x9f54, mkSmc),
    TLV.build(0x9f46, iccPkCert),
    TLV.build(0xdf73, iccRsaPriv),
  ]);

  // --- DGI 9201 — MChip scheme data ---
  // CVR-Default is the 5-byte CVR template MChip seeds at perso time.
  // We synthesise a conservative default (all zero) — it gets mutated
  // at transaction time.  iCVV is referenced by some CVN variants and
  // included here even though Track 2 also carries it.
  const cvrDefault = Buffer.alloc(5, 0x00);

  const dgi9201 = Buffer.concat([
    TLV.build(0x9f52, cvrDefault),   // CVR-Default (proprietary use of 9F52 in MChip 9201)
    TLV.build(0x9f0d, iacDefault),
    TLV.build(0x9f0e, iacDenial),
    TLV.build(0x9f0f, iacOnline),
    TLV.build(0x8e, cvmList),
    TLV.build(0xdf74, icvv),         // iCVV for CVN 18 offline verify
  ]);

  return { dgi0101, dgi0102, dgi8201, dgi9201 };
}

/** Convert BCD bytes to digit string, dropping any trailing 0xF padding. */
function bcdToDigits(bcd: Buffer): string {
  let out = '';
  for (let i = 0; i < bcd.length; i++) {
    out += ((bcd[i] >> 4) & 0x0f).toString(16);
    out += (bcd[i] & 0x0f).toString(16);
  }
  return out.replace(/f+$/i, '').toUpperCase();
}

/**
 * Convert BCD bytes to digit string WITHOUT stripping 'F' padding.
 * Used for fields like serviceCode that are BCD-packed with a leading
 * zero (not 0xF) rather than 'F'-padded at the tail.
 */
function bcdToDigitsNoFPad(bcd: Buffer): string {
  let out = '';
  for (let i = 0; i < bcd.length; i++) {
    out += ((bcd[i] >> 4) & 0x0f).toString(10);
    out += (bcd[i] & 0x0f).toString(10);
  }
  return out;
}
